### ISSUE TITLE
Please Merge

### ISSUE THREAD

**Issue by alishanvr** [therightsol/matproject#1]
Please merge all of your latest code / revisions to this project.

Do not commit / merge at same time. please contact each other before making any commit. for any kind of help, please contact to @abdulshakoor3210 

Individuals tasks will updated tomorrow. And do merging before tomorrow evening. 

Thank You.

@saadzaidi 
@abdulshakoor3210 
@rashidjaved8080 
furqan

**Comment by saadzaidi** [comment]
Sir latest update is submitted by @abdulshakoor3210  already please assign us new task so we can do some work before next class

**Comment by alishanvr** [comment]
ok
