### ISSUE TITLE
Signin Form [Important]

### ISSUE THREAD

**Issue by alishanvr** [therightsol/matproject#13]
@saadzaidi 

Please set each and every thing related to login form. i.e. error handling, wrong input handling, form submission etc. 

When user enter a valid email address and valid password (means when form validate) then it should get record from database for this relevant email.

mean k jo user nai login field mai email dala hai es ka record ap nai fetch krvana hai. aur phr var_export kr dena hai. baqi mai class mai krvao ga. 

agr es user ka email registered hi nai (mean k ap ko db empty array) dy rha hai too phr ap nai user ko message show krvana hai k "This email is not registered."

Due Date: 21 June 2016 (Before Class)

**Comment by saadzaidi** [comment]
ok

**Comment by saadzaidi** [comment]
errors are displaying if email or user name already exist but on next page

**Comment by alishanvr** [comment]
What is status of this issue ? if completed then close else msg me in group.
