### ISSUE TITLE
Design Search Result page

### ISSUE THREAD

**Issue by alishanvr** [therightsol/matproject#15]
@abdullahchaudary 

Design Search result page. it should design with bootstrap. But you need to customize in a way that it should look like margo. Use margo builtin classes. and if some place you did not found any relevant class then you are free to add your custom design in custom.css file. 

You can search google with some keywords like dating websites, matrimonial websites and then check there search result page. 

Keep in mind that:
your designed page should be responsive and should meed quality and standards. 
there should a profile photo, sect, age and short description with read more link.
use card layout. as it is more attractive. but not required. you can design your own. 

@abdullahchaudary 
Due Date: 24 June 2016

**Comment by abdullahchaudary** [comment]
Search page designed
