### ISSUE TITLE
Set Verify page [IMPORTANT]

### ISSUE THREAD

**Issue by alishanvr** [therightsol/matproject#16]
@Furqanafzal 
@abdullahchaudary 

Please set verify page. 

Logic is as under.

When you creates a new account, system will send you verification email link.  click on that link and if email verified then display a message to user that "Congratulations, your email has been verified and now you can login -- Login URL -- "

and if after verification once, user again click on same verification link then display message that your token has been expired. 
REF: Controller / verify . php [LINE : 68]

Please note that, You both should have to complete register page issue as well as this issue. 

Due Date: 
22 June 2016 (Before Class)

**Comment by alishanvr** [comment]
@Furqanafzal 
@abdullahchaudary 

what is status of this issue ? if completed then close it with comment.

**Comment by abdullahchaudary** [comment]
This issue have been resolved!,
