### ISSUE TITLE
Set these pages

### ISSUE THREAD

**Issue by alishanvr** [therightsol/matproject#2]
@saadzaidi 

Please set Login, Register, Reset Password page.

You need to create controller(s) accordingly. Set form names, placeholders, designs, form action etc accordingly.

Check if post or not. and in the Post , check is form is submitted with valid values. If not then show / display error messages. Else display "Pending".

Display pending in case, if user submits form correctly. 

We will do this in future.

**Due Time:**

Register Page :    09 June 2016 (before class)
Other pages :       10 June 2016

**Please Note:**
After due date you have to give aftar party.

**Comment by saadzaidi** [comment]
Sir i have done changes in form its difficult but i have done new design is available now thanx but some issues we will discuss in class thanx
