### ISSUE TITLE
Design Search Member Page

### ISSUE THREAD

**Issue by alishanvr** [therightsol/matproject#3]
@abdulshakoor3210 
@saadzaidi 

Please design and develop Search Page. 

**Usage of Search Page:**

User can search for other member. Please read documentation / use case to get clear view. 
Use case label "Search For Member" please check this in use case diagram. 

You need to create controller and view. In addition, check if post or not. if post then check if form is submitted with valid values or not. If not then show error messages, and if yes then echo "Pending"

We will do this in future.

**Due Date:**
12 June 2016

**Please Note:**
After due date you have to give aftar party.

**Comment by alishanvr** [comment]
@saadzaidi 

This is a warning message to Mr. @saadzaidi . Please do not close any issue that is not completed yet. After completing, Test your work properly and then close the issue. 

@saadzaidi 
Please do not work on this issue in future. I assign you an important work related to register / login page. Please finalize that work till our next class. 

@abdulshakoor3210 
@rashidjaved8080 
You both are assigned to do complete this issue till 17 June 2016.

Do not close issue if pending or not completed.

**Comment by saadzaidi** [comment]
this work is now assign to rashid thats why i close it sir becoz i have designed all forms now its rashid work to allign them

**Comment by alishanvr** [comment]
@saadzaidi 

this work is again assigned to you. 

agr kisi ko b koi tasks sy change kr dia jaye too koi b dosry ka issue close ni kry.
