### ISSUE TITLE
Update Database (SQL) File

### ISSUE THREAD

**Issue by alishanvr** [therightsol/matproject#7]
Please update (SQL) file. change table name to users.

Get sql file from @rashidjaved8080  or from any other colleague. OR create your own file using MySQL Workbench.

We will use this file in our next lecture. So, you have an sql updated file till next lecture. 

Due Date:
@abdulshakoor3210 
10 June 2016 (Before Class)

**Comment by rashidjaved8080** [comment]
Rashidjaved8080@gmil.com
