### ISSUE TITLE
Set Register Form [Important]

### ISSUE THREAD

**Issue by alishanvr** [therightsol/matproject#9]
@saadzaidi 

1)    Please set registration form in order that all relevant should display properly. 

2)    Add your JS so that image should be full size. [HINT] You can use CSS property background-size instead of using JS.

3)    After attaching JS, if you will check Console, then you will find some errors. please fix those errors too. [HINT] Do not use JS. At this stage we does not need JS. (if you are using js only for background image setting)

4)    Login page should be properly set, should display errors. and on success display "Pending" message. we will do this in class.

5)     Properly use action attributes and other HTML, PHP. I have no time to investigate all these in class. I hope you can understand.

Due Date:
16 June 2016
Before Class

**Comment by saadzaidi** [comment]
ok

**Comment by saadzaidi** [comment]
registration page set displaying all errors properly
background image is fully set
login page set displaying all error properly

**Comment by alishanvr** [comment]
@saadzaidi 
login page is not showing errors properly. 

please test and fix these issues by next class.

**Comment by saadzaidi** [comment]
login page is displaying errors sir humne login abi ni kia class mai so jo user db mai hn wo login agr krte hn uske jo errors hn wo kaise krwane hn show jb tk login ni kr lete hum
